'use strict';
(function(){
  const KEY='mi-control.entries.v1';
  const TZ='Europe/Madrid';
  const $=id=>document.getElementById(id);
  const money=v=>Math.round((Number(v)||0)*100)/100;
  const net=e=>money((Number(e.returned)||0)-(Number(e.stake)||0));
  const dateObj=s=>{const d=new Date(`${s}T00:00:00Z`);return Number.isNaN(d.getTime())?null:d};
  const iso=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`};
  const startWeek=s=>{const d=dateObj(s);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d};
  function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
  function activePeriod(){return document.querySelector('#periods button.active')?.dataset.period||'week'}
  function filtered(){const entries=load().slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))||(Number(a.createdAt)||0)-(Number(b.createdAt)||0));const p=activePeriod(),today=iso(),now=dateObj(today);if(p==='all')return entries;if(p==='today')return entries.filter(e=>e.date===today);if(p==='week'){const s=startWeek(today),end=new Date(s);end.setUTCDate(s.getUTCDate()+7);return entries.filter(e=>{const d=dateObj(e.date);return d&&d>=s&&d<end})}return entries.filter(e=>{const d=dateObj(e.date);return d&&d.getUTCFullYear()===now.getUTCFullYear()&&d.getUTCMonth()===now.getUTCMonth()})}
  function byDay(entries){const map=new Map();for(const e of entries)map.set(e.date,money((map.get(e.date)||0)+net(e)));return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
  function draw(){const c=$('chart');if(!c||!c.isConnected)return;const ctx=c.getContext('2d'),r=c.getBoundingClientRect();if(!ctx||!r.width)return;const dpr=window.devicePixelRatio||1,w=r.width,h=210,pad=30;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const days=byDay(filtered());let cumulative=0;const pts=days.map(([date,value])=>({date,value:cumulative=money(cumulative+value)}));if(!pts.length)pts.push({date:iso(),value:0});const values=[0,...pts.map(x=>x.value)],min=Math.min(...values),max=Math.max(...values),rawSpan=max-min,span=Math.max(20,rawSpan),extra=span*.16,lo=min-extra,hi=max+extra,total=hi-lo;const y=v=>h-pad-((v-lo)/total)*(h-pad*2);ctx.lineWidth=1;ctx.strokeStyle='rgba(100,116,139,.18)';for(let i=0;i<5;i++){const yy=pad+(h-pad*2)*i/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad,yy);ctx.stroke()}const zeroY=y(0);ctx.strokeStyle='rgba(71,85,105,.42)';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(pad,zeroY);ctx.lineTo(w-pad,zeroY);ctx.stroke();ctx.setLineDash([]);const step=(w-pad*2)/Math.max(1,pts.length-1),coords=pts.map((point,i)=>({x:pts.length===1?w/2:pad+i*step,y:y(point.value),value:point.value}));const color=cumulative<0?'#ef4444':cumulative>0?'#22c55e':'#6d5dfc';if(coords.length>1){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();coords.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.stroke()}ctx.fillStyle=color;for(const q of coords){ctx.beginPath();ctx.arc(q.x,q.y,4,0,Math.PI*2);ctx.fill()}ctx.font='700 12px system-ui,-apple-system,sans-serif';ctx.textAlign='right';ctx.fillStyle=color;ctx.fillText(`${cumulative>0?'+':''}${cumulative.toFixed(2).replace('.',',')} €`,w-pad,18);const totalEl=$('chartTotal');if(totalEl){totalEl.style.color=color;totalEl.textContent=`${cumulative>0?'+':''}${new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(cumulative)}`}}
  function later(){requestAnimationFrame(()=>requestAnimationFrame(draw))}
  document.addEventListener('DOMContentLoaded',later);window.addEventListener('pageshow',later);window.addEventListener('storage',later);window.addEventListener('resize',later);document.addEventListener('visibilitychange',()=>{if(!document.hidden)later()});document.addEventListener('click',e=>{if(e.target.closest('#save,#periods button,[data-del],#undoDelete,#importData,#tabInvest,#navHome'))setTimeout(later,40)});const observer=new MutationObserver(m=>{if(m.some(x=>x.target.id==='chartTotal'||x.target.id==='historyList'||x.target.id==='staked'))setTimeout(later,0)});for(const id of ['chartTotal','historyList','staked']){const el=$(id);if(el)observer.observe(el,{childList:true,subtree:true,characterData:true})}later();
})();